---
title: "pubias: Identification of and Correction for Publication Bias^[This package was created as part of the seminar Workshop in Econometrics (Spring Semester 2021) and follows the implementation by *Andrews, Isaiah, and Maximilian Kasy. 2019. Identification of and Correction for Publication Bias.*]"
author: "Till Sager^[University of Bern, till.sager@students.unibe.ch]"
date: "May, 2021"
output:   
  pdf_document:
    toc: true
    toc_depth: 3  
    number_sections: true 
    latex_engine: xelatex
vignette: >
  %\VignetteIndexEntry{pubias: Identification of and Correction for Publication Bias"}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
)
```

```{r setup}

```


\newpage


# Introduction

# Methods and assumption

## Replication Studies

## Meta Analysis

## MLE

## GMM

# Main functions

## Syntax

## Description

## Arguments

## Results

## Applications

### Replication Study

### Meta Analysis

# Final remarks
