---
title: "Publication Bias correction"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
params: 
  plots: plots
  descriptives: descriptives
  pub_prob: result$Psihat
  
---

```{r setup, include=FALSE}


```


Descriptives
===================================== 


Column {data-width=500}
-----------------------------------------------------------------------

### Histogram

```{r}
suppressWarnings(params$descriptives$hist)
```

Column {data-width=500}
-----------------------------------------------------------------------

### Identification

```{r}
suppressWarnings(params$descriptives$scatter)
```


Correction Plots 
===================================== 

Column {data-width=500}
-----------------------------------------------------------------------

### Publication Probability

```{r}
valueBox(value = paste0(round(100*params$pub_prob,1),"%"), caption = paste0("Results which are insignificant at the given significance level are ",round(100*params$pub_prob,1),"%"," as likely to be published as significant results."), icon = "fa-pencil")
```

### Correction Plot

```{r}
suppressWarnings(params$plots$CorrectionPlot)
```

Column {data-width=500}
-----------------------------------------------------------------------

### Original and adjusted estimates

```{r}
suppressWarnings(params$plots$OriginalAndAdjusted)
```

### Original and adjusted estimates, including Bonferroni CIs

```{r}
suppressWarnings(params$plots$OriginalAndAdjustedBonferroni)
```


