---
title: "Publication Bias correction"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
params: 
  plots: plots
  descriptives: descriptives
---

```{r setup, include=FALSE}


```

Descriptives
===================================== 


Column {data-width=500}
-----------------------------------------------------------------------

### Histogram

```{r}
params$descriptives$hist
```

Column {data-width=500}
-----------------------------------------------------------------------

### Funnelplot

```{r}
params$descriptives$scatter
```


Correction Plots 
===================================== 

Column {data-width=500}
-----------------------------------------------------------------------

### Publication Probability

```{r}
valueBox(value = "2.9%", caption = "Results which are insignificant at the 5% level are 2.9% as likely to be
published as significant results.", icon = "fa-pencil")
```

### Correction Plot

```{r}
params$plots$CorrectionPlot
```

Column {data-width=500}
-----------------------------------------------------------------------

### Original and adjusted estimates

```{r}
params$plots$OriginalAndAdjusted
```

### Original and adjusted estimates, including Bonferroni CIs

```{r}
params$plots$OriginalAndAdjustedBonferroni
```
